export const moodButtons = {
  happy: {
    btn: "Happy",
    genres: [
      "acoustic",
      "bossanova",
      "children",
      "comedy",
      "dance",
      "disco",
      "disney",
      "funk",
      "happy",
      "holidays",
      "honky-tonk",
      "party",
      "pop",
      "pop-film",
      "power-pop",
      "reggae",
      "salsa",
      "samba",
      "soul",
      "summer",
      "tango",
    ],
  },
  energized: {
    btn: "Energized",
    genres: [
      "afrobeat",
      "alt-rock",
      "alternative",
      "breakbeat",
      "chicago-house",
      "club",
      "dancehall",
      "drum-and-bass",
      "dubstep",
      "edm",
      "electro",
      "electronic",
      "hip-hop",
      "house",
      "j-dance",
      "j-idol",
      "j-pop",
      "j-rock",
      "techno",
      "trance",
    ],
  },
  relaxed: {
    btn: "Relaxed",
    genres: [
      "ambient",
      "bluegrass",
      "blues",
      "bossanova",
      "chill",
      "classical",
      "indie",
      "indie-pop",
      "jazz",
      "new-age",
      "piano",
      "singer-songwriter",
      "synth-pop",
    ],
  },
  sad: {
    btn: "Sad",
    genres: [
      "acoustic",
      "blues",
      "emo",
      "folk",
      "gospel",
      "grunge",
      "indie",
      "jazz",
      "r-n-b",
      "rainy-day",
      "sad",
      "singer-songwriter",
      "soul",
      "soundtracks",
    ],
  },
  angry: {
    btn: "Angry",
    genres: [
      "black-metal",
      "death-metal",
      "grindcore",
      "hardcore",
      "hard-rock",
      "hardstyle",
      "heavy-metal",
      "metal",
      "metal-misc",
      "metalcore",
      "punk",
      "punk-rock",
    ],
  },
};
